name: m4sport

services:
  scraper:
    build:
      context: ./src/scraper
    volumes:
      - ./scraped:/app/scraped

  player:
    build:
      context: ./src/player
    volumes:
      - ./scraped:/usr/local/apache2/htdocs/scraped
    ports:
      - "8080:80"
