name: m4sport

services:
  scraper:
    build:
      context: ./src/scraper
    volumes:
      - ./scraped:/app/scraped
    environment:
      - CRON_SCHEDULE=* * * * *
      - TZ=Europe/Budapest

  player:
    build:
      context: ./src/player
    volumes:
      - ./scraped:/usr/share/nginx/html/scraped
    ports:
      - "8080:80"
